runtime: nodejs10
env: standard
env_variables:
  API_URL: 'https://monitory-363ae.appspot.com'
  PORT: 8080
  NODE_ENV: 'development'
  PUBLIC_URL: 'https://monitory-363ae.appspot.com'
  DB_DIALECT: 'postgres'
  DB_HOST: '***REMOVED***'
  DB_USER: 'monitory'
  DB_PASS: '***REMOVED***'
  DB_NAME: 'monitory'
  GCLOUD_PROJECT: 'monitory-363ae'
  GCLOUD_BUCKET: 'monitory-363ae'
  SENTRY_DSN: '***REMOVED***'
beta_settings:
  cloud_sql_instances: [***REMOVED***]
